services:
  # FastAPI app service
  fastapi_backend:
    build: .
    container_name: fastapi_backend
    image: fastapi_backend
    restart: always
    ports:
      - "${DOCKER_PORT:-8000}:8000"
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - ${LOG_DIR:-./logs}:/app/logs
    networks:
      - custom-network
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers 4 --timeout-keep-alive 60

networks:
  custom-network:
    driver: bridge
